name: 🛠️ Build with Gradle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code and clone submodules
      - name: Checkout code and clone submodules
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # Step 3: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      # Step 4: Grant execute permissions to gradlew
      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build